-- ============================================================
-- SVWS 26 — Nâng cấp Mô tả công việc (JD) chuyên nghiệp, đầy đủ, đúng luật
--   • Mở rộng mục đích / trách nhiệm / quyền hạn / yêu cầu cho 15 vị trí
--   • Bổ sung trong yeu_cau: chung_chi, dieu_kien (điều kiện làm việc),
--     tuan_thu (tuân thủ BLLĐ 45/2019/QH14, Luật ATVSLĐ 84/2015/QH13...)
-- ============================================================
BEGIN;

-- ---------- CEO ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Giám đốc điều hành', cap_bac='Điều hành', bao_cao_cho='HĐTV / Chủ sở hữu',
 muc_dich=$jd$Chịu trách nhiệm cao nhất trước Hội đồng thành viên về định hướng chiến lược, kết quả kinh doanh, tuân thủ pháp luật và sự phát triển bền vững của công ty trong lĩnh vực xử lý nước cấp, nước thải và khí thải; là người đại diện theo pháp luật của công ty.$jd$,
 trach_nhiem=$jd$["Hoạch định chiến lược phát triển, kế hoạch kinh doanh năm và phân bổ nguồn lực, chỉ tiêu cho các phòng ban.","Phê duyệt hợp đồng, dự án đầu tư, chính sách giá và mọi quyết định vượt hạn mức của cấp dưới.","Phê duyệt ma trận phân quyền hệ thống, bổ nhiệm - miễn nhiệm vị trí quản lý (Overall Operation).","Giám sát dòng tiền, hiệu quả tài chính, công nợ và quản trị rủi ro toàn công ty.","Ký duyệt cuối bảng lương, báo cáo tài chính và các hồ sơ pháp lý trọng yếu.","Phát triển quan hệ đối tác chiến lược, khách hàng trọng điểm và uy tín thương hiệu.","Bảo đảm công ty tuân thủ pháp luật lao động, thuế, môi trường và ATVSLĐ; chịu trách nhiệm người sử dụng lao động theo BLLĐ 2019.","Xây dựng văn hóa doanh nghiệp, quy hoạch đội ngũ kế thừa và chính sách đãi ngộ."]$jd$,
 quyen_han=$jd$["Toàn quyền phê duyệt mọi nghiệp vụ, hạn mức và phân quyền trong hệ thống.","Quyết định tuyển dụng, bổ nhiệm, miễn nhiệm, khen thưởng, kỷ luật mọi vị trí.","Đại diện công ty ký kết hợp đồng, giao dịch với đối tác, cơ quan nhà nước.","Quyết định cơ cấu tổ chức, thành lập/giải thể bộ phận.","Ủy quyền có thời hạn cho cấp quản lý khi vắng mặt."]$jd$,
 yeu_cau=$jd${"hoc_van":"Đại học trở lên chuyên ngành Kỹ thuật môi trường, Cấp thoát nước hoặc Quản trị kinh doanh; ưu tiên sau đại học.","kinh_nghiem":"≥ 10 năm trong ngành nước/môi trường, trong đó ≥ 5 năm quản lý cấp cao.","ky_nang":["Tư duy chiến lược","Quản trị tài chính doanh nghiệp","Lãnh đạo & xây dựng đội ngũ","Đàm phán cấp cao","Quản trị rủi ro & tuân thủ"],"chung_chi":"Ưu tiên chứng chỉ quản trị doanh nghiệp (CEO/Mini-MBA) hoặc tương đương.","dieu_kien":["Thời giờ làm việc theo BLLĐ 2019: 8 giờ/ngày, không quá 48 giờ/tuần; chủ động thời gian theo yêu cầu điều hành.","Địa điểm: trụ sở 448 Võ Văn Tần, Q.3, TP.HCM; công tác trong và ngoài nước theo nhu cầu.","Được cấp phương tiện làm việc, chi phí công tác và các quyền lợi cấp điều hành.","Tham gia BHXH, BHYT, BHTN đầy đủ; khám sức khỏe định kỳ hằng năm; nghỉ phép năm theo luật."],"tuan_thu":["Thực hiện nghĩa vụ người đại diện theo pháp luật và người sử dụng lao động theo BLLĐ 45/2019/QH14.","Bảo đảm công ty chấp hành Luật ATVSLĐ 84/2015/QH13, Luật BHXH, pháp luật thuế và môi trường.","Bảo mật bí mật kinh doanh, bí mật công nghệ theo Điều 21 BLLĐ và điều lệ công ty.","Chấp hành nội quy lao động, quy chế tài chính và điều lệ công ty."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='CEO';

-- ---------- TP_KD ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Trưởng phòng Kinh doanh', cap_bac='Quản lý', bao_cao_cho='CEO',
 muc_dich=$jd$Dẫn dắt đội ngũ kinh doanh đạt mục tiêu doanh số và tăng trưởng thị phần các giải pháp xử lý nước/nước thải/khí thải; chịu trách nhiệm về chất lượng phễu cơ hội, chính sách giá và sự hài lòng của khách hàng trước Giám đốc.$jd$,
 trach_nhiem=$jd$["Lập kế hoạch kinh doanh quý/năm; phân bổ và theo dõi chỉ tiêu doanh số từng nhân viên.","Phê duyệt báo giá trong hạn mức 100 triệu đồng; kiểm soát chính sách giá, chiết khấu, điều khoản thanh toán.","Quản lý phễu cơ hội trên hệ thống: dự báo doanh số, tỷ lệ chuyển đổi, nguyên nhân thắng/thua.","Trực tiếp phát triển khách hàng lớn, đối tác chiến lược và kênh dự án.","Duyệt nội dung chiến dịch email chào hàng trước khi gửi; giám sát chất lượng chăm sóc khách hàng.","Phối hợp Phòng Dự án thẩm định tính khả thi kỹ thuật và giá vốn trước khi báo giá.","Huấn luyện, kèm cặp, đánh giá KPI đội ngũ kinh doanh và CRM.","Báo cáo tình hình kinh doanh định kỳ cho Giám đốc; đề xuất điều chỉnh chiến lược."]$jd$,
 quyen_han=$jd$["Duyệt báo giá, đơn hàng trong hạn mức được giao (≤ 100 triệu đồng).","Phân bổ, điều chỉnh chỉ tiêu và địa bàn trong nội bộ phòng.","Đề xuất tuyển dụng, khen thưởng, kỷ luật nhân sự thuộc phòng.","Đề xuất chính sách giá, chương trình khuyến mãi lên Giám đốc.","Đại diện công ty đàm phán với khách hàng trong phạm vi được ủy quyền."]$jd$,
 yeu_cau=$jd${"hoc_van":"Đại học chuyên ngành Kỹ thuật (Môi trường/Cấp thoát nước) hoặc Kinh tế; ưu tiên có cả hai nền tảng.","kinh_nghiem":"≥ 5 năm kinh doanh giải pháp kỹ thuật B2B, ≥ 2 năm quản lý đội nhóm.","ky_nang":["Bán giải pháp B2B","Quản lý & phát triển đội ngũ","Dự báo - phân tích số liệu","Đàm phán hợp đồng","Thuyết trình giải pháp kỹ thuật"],"chung_chi":"Ưu tiên chứng chỉ quản trị bán hàng chuyên nghiệp.","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7; làm thêm giờ theo thỏa thuận, không vượt giới hạn Điều 107 BLLĐ 2019.","Địa điểm: văn phòng công ty; thường xuyên đi thị trường, gặp khách hàng, tham dự thầu.","Được cấp laptop, tài khoản hệ thống SVWS, sim công việc và chi phí công tác theo quy chế.","Lương thỏa thuận + thưởng doanh số; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày; khám sức khỏe định kỳ."],"tuan_thu":["Thực hiện đúng hợp đồng lao động, nội quy lao động theo BLLĐ 45/2019/QH14.","Bảo mật thông tin khách hàng, chính sách giá, bí mật kinh doanh theo Điều 21 BLLĐ và cam kết bảo mật.","Không nhận hoa hồng, quà tặng trái quy định từ khách hàng/đối tác (quy chế chống tham nhũng nội bộ).","Chấp hành quy định ATVSLĐ và an toàn giao thông khi công tác hiện trường."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='TP_KD';

-- ---------- NV_KD ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Nhân viên Kinh doanh', cap_bac='Nhân viên', bao_cao_cho='TP_KD',
 muc_dich=$jd$Tìm kiếm, tư vấn và chốt hợp đồng các giải pháp xử lý nước cho khách hàng công nghiệp; xây dựng quan hệ lâu dài và chăm sóc danh mục khách hàng được giao nhằm hoàn thành chỉ tiêu doanh số cá nhân.$jd$,
 trach_nhiem=$jd$["Khai thác khách hàng tiềm năng qua đi thị trường, hội thảo, giới thiệu và các kênh trực tuyến.","Khảo sát nhu cầu, thu thập thông số nước thải/nước cấp; phối hợp kỹ thuật đề xuất giải pháp phù hợp.","Soạn và gửi báo giá trên hệ thống; theo dõi phản hồi, đàm phán và trình duyệt theo hạn mức.","Cập nhật đầy đủ cơ hội, liên lạc, công việc vào hệ thống CRM; giữ dữ liệu khách hàng chính xác.","Theo dõi tiến độ giao hàng, nghiệm thu và hỗ trợ thu hồi công nợ của khách phụ trách.","Chăm sóc sau bán: thăm hỏi định kỳ, ghi nhận phản hồi, phối hợp xử lý khiếu nại trong SLA.","Tham gia hội chợ, sự kiện ngành nước theo phân công.","Báo cáo tuần về phễu cơ hội, kết quả và kế hoạch hành động cho Trưởng phòng."]$jd$,
 quyen_han=$jd$["Lập báo giá, đơn hàng, hợp đồng trên hệ thống (trình duyệt theo hạn mức).","Đề xuất chiết khấu trong khung chính sách giá được công bố.","Chủ động sắp xếp lịch gặp khách trong địa bàn được giao.","Đề xuất chương trình chăm sóc, quà tặng khách hàng theo quy chế."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học; ưu tiên Kỹ thuật môi trường, Hóa, Cấp thoát nước hoặc QTKD.","kinh_nghiem":"≥ 1 năm bán hàng kỹ thuật B2B; sinh viên mới tốt nghiệp khá giỏi có thể đào tạo.","ky_nang":["Tư vấn giải pháp","Giao tiếp - thuyết phục","Lập báo giá & hồ sơ thầu","Chăm sóc khách hàng","Tin học văn phòng & CRM"],"chung_chi":"Bằng lái xe A1/B2 là lợi thế (đi thị trường).","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7; linh hoạt khi gặp khách theo lịch hẹn.","Địa điểm: văn phòng + đi thị trường thường xuyên trong khu vực được phân công.","Được cấp máy tính, tài khoản hệ thống, hỗ trợ chi phí đi lại - điện thoại theo quy chế.","Lương cơ bản + hoa hồng doanh số; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày."],"tuan_thu":["Thực hiện đúng hợp đồng lao động và nội quy lao động theo BLLĐ 45/2019/QH14.","Bảo mật thông tin khách hàng, giá bán, bí mật kinh doanh theo Điều 21 BLLĐ.","Giao dịch trung thực; nghiêm cấm thỏa thuận riêng với khách hàng ngoài hệ thống.","Chấp hành ATVSLĐ, an toàn giao thông khi công tác."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='NV_KD';

-- ---------- NV_CRM ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Nhân viên Chăm sóc Khách hàng', cap_bac='Nhân viên', bao_cao_cho='TP_KD',
 muc_dich=$jd$Duy trì và nâng cao sự hài lòng của khách hàng sau bán hàng; quản lý hồ sơ khách hàng 360°, lịch chăm sóc định kỳ và xử lý khiếu nại đúng SLA nhằm tăng tỷ lệ mua lại và giới thiệu.$jd$,
 trach_nhiem=$jd$["Quản lý hồ sơ khách hàng 360° trên hệ thống: thông tin liên hệ, lịch sử giao dịch, công nợ, phản hồi.","Thực hiện lịch chăm sóc sau bán (+7/+30 ngày sau giao hàng): gọi điện, email, ghi nhận CSAT.","Tiếp nhận khiếu nại qua mọi kênh, ghi nhận vào hệ thống và điều phối xử lý trong SLA 24 giờ.","Theo dõi hộp thư phản hồi; phân loại, trả lời hoặc chuyển đúng bộ phận xử lý.","Nhắc lịch bảo trì, gia hạn hợp đồng, sinh nhật/dịp đặc biệt của khách hàng.","Tổng hợp báo cáo CSAT, khiếu nại, tỷ lệ giữ chân khách hàng theo tháng.","Phối hợp kinh doanh cập nhật phân hạng khách hàng A/B/C.","Đề xuất cải tiến quy trình chăm sóc từ phản hồi thực tế của khách."]$jd$,
 quyen_han=$jd$["Ghi nhận, cập nhật thông tin và lịch sử chăm sóc mọi khách hàng.","Liên hệ trực tiếp khách hàng nhân danh công ty theo kịch bản đã duyệt.","Yêu cầu các bộ phận phối hợp xử lý khiếu nại trong SLA.","Đề xuất phương án đền bù/ưu đãi cho khách (trình duyệt)."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học các ngành Kinh tế, QTKD, Ngoại ngữ hoặc liên quan.","kinh_nghiem":"≥ 1 năm chăm sóc khách hàng/CSKH tổng đài; ưu tiên môi trường B2B.","ky_nang":["Giao tiếp điện thoại & email chuyên nghiệp","Lắng nghe - xử lý than phiền","Quản lý dữ liệu CRM","Soạn thảo văn bản","Ngoại ngữ giao tiếp là lợi thế"],"chung_chi":"","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7 tại văn phòng công ty.","Được cấp máy tính, tổng đài/điện thoại công việc và tài khoản hệ thống SVWS.","Lương thỏa thuận + thưởng CSAT; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày.","Môi trường văn phòng; hiếm khi công tác hiện trường."],"tuan_thu":["Thực hiện đúng hợp đồng lao động, nội quy lao động theo BLLĐ 45/2019/QH14.","Bảo mật dữ liệu cá nhân của khách hàng theo Nghị định 13/2023/NĐ-CP về bảo vệ dữ liệu cá nhân.","Giao tiếp đúng chuẩn mực thương hiệu; không cam kết vượt thẩm quyền.","Ghi nhận trung thực mọi phản hồi, khiếu nại vào hệ thống."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='NV_CRM';

-- ---------- TP_CU ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Trưởng phòng Cung ứng', cap_bac='Quản lý', bao_cao_cho='CEO',
 muc_dich=$jd$Bảo đảm nguồn cung vật tư, thiết bị, hóa chất đúng chất lượng - đúng tiến độ - tối ưu chi phí cho toàn bộ hoạt động dự án, bảo trì và cho thuê; quản trị quan hệ và rủi ro nhà cung cấp.$jd$,
 trach_nhiem=$jd$["Duyệt đề xuất mua hàng và đơn mua (PO) trong hạn mức 10 triệu đồng; trình Giám đốc phần vượt.","Xây dựng và quản lý danh mục nhà cung cấp: đánh giá năng lực, chấm điểm định kỳ, xử lý blacklist.","Tổ chức hỏi giá (RFQ), so sánh, đàm phán giá và điều khoản với nhà cung cấp.","Kiểm soát tồn kho min-max, phê duyệt kế hoạch mua bù tồn và mua theo dự án.","Giám sát tiến độ giao hàng, chất lượng đầu vào và xử lý hàng lỗi/thiếu.","Kiểm soát công nợ phải trả, phối hợp Kế toán lập lịch thanh toán nhà cung cấp.","Xây dựng quy trình mua hàng minh bạch; luân chuyển hồ sơ đầy đủ trên hệ thống.","Đào tạo, đánh giá nhân viên mua hàng và thủ kho."]$jd$,
 quyen_han=$jd$["Duyệt đề xuất mua và PO trong hạn mức (≤ 10 triệu đồng).","Phê duyệt danh sách nhà cung cấp đủ điều kiện; đề xuất blacklist.","Đàm phán, ký biên bản làm việc với nhà cung cấp trong phạm vi ủy quyền.","Yêu cầu bộ phận đề xuất bổ sung hồ sơ, dự toán trước khi duyệt.","Đề xuất nhân sự, khen thưởng, kỷ luật trong phòng."]$jd$,
 yeu_cau=$jd${"hoc_van":"Đại học Kinh tế, Ngoại thương, Kỹ thuật hoặc chuỗi cung ứng.","kinh_nghiem":"≥ 5 năm mua hàng công nghiệp/thiết bị, ≥ 2 năm quản lý.","ky_nang":["Đàm phán & quản trị nhà cung cấp","Phân tích giá & tổng chi phí sở hữu (TCO)","Quản lý tồn kho","Hợp đồng thương mại","Excel/hệ thống ERP"],"chung_chi":"Ưu tiên chứng chỉ mua hàng - chuỗi cung ứng (CIPS/CPSM hoặc tương đương).","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7 tại văn phòng; đi đánh giá nhà cung cấp khi cần.","Được cấp máy tính, tài khoản hệ thống và chi phí công tác theo quy chế.","Lương thỏa thuận; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày; khám sức khỏe định kỳ."],"tuan_thu":["Thực hiện đúng hợp đồng lao động, nội quy lao động theo BLLĐ 45/2019/QH14.","Tuân thủ quy chế mua hàng, chống xung đột lợi ích; kê khai quan hệ với nhà cung cấp (nếu có).","Nghiêm cấm nhận hoa hồng, quà tặng trái quy định từ nhà cung cấp (Luật Phòng, chống tham nhũng 2018).","Bảo mật giá mua, điều khoản hợp đồng theo Điều 21 BLLĐ."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='TP_CU';

-- ---------- NV_MUA ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Nhân viên Mua hàng', cap_bac='Nhân viên', bao_cao_cho='TP_CU',
 muc_dich=$jd$Thực hiện quy trình mua vật tư, thiết bị, hóa chất từ đề xuất đến nhập kho đúng tiến độ, đúng chất lượng và đúng quy trình; duy trì dữ liệu giá và hồ sơ nhà cung cấp đầy đủ trên hệ thống.$jd$,
 trach_nhiem=$jd$["Tiếp nhận đề xuất mua đã duyệt; lập RFQ gửi tối thiểu 2-3 nhà cung cấp cho đơn giá trị lớn.","So sánh báo giá, lập bảng phân tích và đề xuất lựa chọn nhà cung cấp trình Trưởng phòng.","Lập PO trên hệ thống, theo dõi xác nhận, tiến độ sản xuất và giao hàng của nhà cung cấp.","Phối hợp thủ kho kiểm nhận hàng: số lượng, chủng loại, CO/CQ, MSDS với hóa chất.","Cập nhật đơn giá, thời gian giao, đánh giá chất lượng của từng nhà cung cấp sau mỗi đơn.","Theo dõi công nợ phải trả và tập hợp chứng từ thanh toán chuyển Kế toán.","Xử lý hàng lỗi, thiếu, trả hàng, bảo hành với nhà cung cấp.","Tìm kiếm, sàng lọc nhà cung cấp mới theo định hướng của Trưởng phòng."]$jd$,
 quyen_han=$jd$["Liên hệ, yêu cầu báo giá và thông tin kỹ thuật từ nhà cung cấp.","Lập PO trên hệ thống (hiệu lực sau khi được duyệt).","Từ chối nhận hàng không đúng chủng loại, thiếu chứng từ chất lượng.","Đề xuất nhà cung cấp mới, loại nhà cung cấp yếu kém."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học Kinh tế, Kỹ thuật hoặc liên quan.","kinh_nghiem":"≥ 1 năm mua hàng, ưu tiên vật tư công nghiệp/thiết bị ngành nước.","ky_nang":["So sánh - đàm phán giá","Đọc thông số kỹ thuật cơ bản","Quản lý chứng từ","Excel thành thạo","Giao tiếp với nhà cung cấp"],"chung_chi":"","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7 tại văn phòng; thỉnh thoảng đi kho/nhà cung cấp.","Được cấp máy tính, tài khoản hệ thống SVWS.","Lương thỏa thuận; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày."],"tuan_thu":["Thực hiện đúng hợp đồng lao động, nội quy lao động theo BLLĐ 45/2019/QH14.","Tuân thủ quy trình mua hàng; mọi giao dịch phải qua hệ thống, có phê duyệt.","Nghiêm cấm nhận hoa hồng, lợi ích riêng từ nhà cung cấp.","Bảo mật giá mua và thông tin thương mại theo Điều 21 BLLĐ."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='NV_MUA';

-- ---------- THUKHO ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Thủ kho', cap_bac='Nhân viên', bao_cao_cho='TP_CU',
 muc_dich=$jd$Quản lý kho vật tư, thiết bị, hóa chất chính xác - an toàn - ngăn nắp; bảo đảm số liệu tồn kho trên hệ thống luôn khớp thực tế và hàng hóa được bảo quản đúng tiêu chuẩn, đặc biệt hóa chất nguy hiểm.$jd$,
 trach_nhiem=$jd$["Thực hiện nhập - xuất kho theo phiếu trên hệ thống; kiểm đếm, đối chiếu chứng từ trước khi ký nhận.","Sắp xếp kho theo sơ đồ, dán nhãn, FIFO/FEFO với hóa chất có hạn dùng.","Bảo quản hóa chất đúng MSDS: phân khu riêng, thông gió, chống tràn đổ, đầy đủ biển cảnh báo.","Theo dõi tồn min-max, cảnh báo Trưởng phòng khi hàng sắp hết hoặc tồn đọng lâu.","Tham gia kiểm kê định kỳ và đột xuất; giải trình chênh lệch, lập biên bản điều chỉnh.","Quản lý thiết bị, dụng cụ cho mượn ra công trường: sổ theo dõi, tình trạng khi trả.","Duy trì 5S và điều kiện an toàn kho: PCCC, chống dột, khóa và camera.","Cập nhật thẻ kho, hồ sơ nhập xuất đầy đủ phục vụ kế toán và kiểm toán."]$jd$,
 quyen_han=$jd$["Từ chối nhập/xuất khi chứng từ chưa hợp lệ hoặc chưa được duyệt trên hệ thống.","Từ chối nhận hàng sai quy cách, không nhãn mác, thiếu MSDS với hóa chất.","Đề xuất thanh lý hàng hư hỏng, tồn đọng; đề xuất cải tạo điều kiện kho.","Yêu cầu người vào kho tuân thủ quy định an toàn."]$jd$,
 yeu_cau=$jd${"hoc_van":"Trung cấp trở lên; ưu tiên ngành kho vận, hóa chất, cơ khí.","kinh_nghiem":"≥ 1 năm thủ kho công nghiệp; ưu tiên đã quản lý kho hóa chất.","ky_nang":["Nghiệp vụ kho & thẻ kho","Sử dụng phần mềm quản lý kho","An toàn hóa chất (đọc MSDS)","5S","Vận hành xe nâng tay/thiết bị nâng hạ cơ bản"],"chung_chi":"Chứng nhận huấn luyện ATVSLĐ nhóm liên quan; chứng chỉ an toàn hóa chất theo Nghị định 113/2017/NĐ-CP là lợi thế.","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7 tại kho công ty.","Được cấp đầy đủ phương tiện bảo hộ: găng, kính, khẩu trang phòng độc khi tiếp xúc hóa chất.","Môi trường kho có hóa chất - yêu cầu tuân thủ nghiêm quy trình an toàn; khám sức khỏe định kỳ theo Luật ATVSLĐ.","Lương thỏa thuận + phụ cấp độc hại theo quy định; BHXH/BHYT/BHTN đầy đủ."],"tuan_thu":["Thực hiện đúng nội quy lao động, quy trình kho theo BLLĐ 45/2019/QH14.","Chấp hành Luật ATVSLĐ 84/2015/QH13 và quy định quản lý hóa chất (Luật Hóa chất 2007, NĐ 113/2017/NĐ-CP).","Tuân thủ PCCC theo Luật PCCC; tham gia đội PCCC cơ sở khi được phân công.","Chịu trách nhiệm vật chất về chênh lệch tồn kho do lỗi chủ quan theo Điều 129 BLLĐ."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='THUKHO';

-- ---------- KTT ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Kế toán trưởng', cap_bac='Quản lý', bao_cao_cho='CEO',
 muc_dich=$jd$Tổ chức bộ máy kế toán - tài chính tuân thủ pháp luật; bảo đảm sổ sách trung thực, báo cáo đúng hạn, kiểm soát chi phí - dòng tiền và cung cấp thông tin quản trị tin cậy cho Giám đốc; thực hiện trách nhiệm Kế toán trưởng theo Luật Kế toán 2015.$jd$,
 trach_nhiem=$jd$["Tổ chức hạch toán kế toán theo chuẩn mực VAS và chế độ kế toán doanh nghiệp (TT 200/2014/TT-BTC).","Lập báo cáo tài chính, báo cáo thuế (GTGT, TNDN, TNCN) đầy đủ, đúng hạn.","Kiểm soát dòng tiền, kế hoạch thanh toán, công nợ phải thu - phải trả và tồn quỹ.","Duyệt phiếu thu/chi trong hạn mức; kiểm soát chứng từ trước khi trình Giám đốc.","Duyệt và hạch toán bảng lương (bước Kế toán trưởng) trước khi Giám đốc ký.","Quản lý hóa đơn điện tử, đối chiếu doanh thu - giá vốn theo mã bán hàng.","Làm việc với cơ quan thuế, kiểm toán, ngân hàng; cập nhật chính sách thuế mới.","Xây dựng quy chế tài chính, kiểm soát nội bộ và đào tạo nhân viên kế toán."]$jd$,
 quyen_han=$jd$["Quyền độc lập về chuyên môn nghiệp vụ kế toán theo Điều 55 Luật Kế toán 2015.","Duyệt bút toán, phiếu thu/chi trong hạn mức; từ chối chứng từ không hợp lệ, không hợp pháp.","Yêu cầu các bộ phận cung cấp đầy đủ, kịp thời chứng từ và tài liệu liên quan.","Duyệt bảng lương bước KTT; đề xuất chính sách tài chính - thuế.","Báo cáo trực tiếp Giám đốc khi phát hiện dấu hiệu vi phạm tài chính."]$jd$,
 yeu_cau=$jd${"hoc_van":"Đại học chuyên ngành Kế toán - Kiểm toán - Tài chính.","kinh_nghiem":"≥ 5 năm kế toán, trong đó ≥ 2 năm Kế toán trưởng hoặc phụ trách kế toán.","ky_nang":["Kế toán tổng hợp & giá thành","Thuế và quyết toán","Phân tích tài chính - dòng tiền","Kiểm soát nội bộ","Phần mềm kế toán/ERP"],"chung_chi":"Bắt buộc có Chứng chỉ Kế toán trưởng theo TT 199/2011/TT-BTC; ưu tiên thêm chứng chỉ hành nghề kế toán/ACCA.","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7 tại văn phòng; cao điểm quyết toán có thể làm thêm giờ theo thỏa thuận.","Được cấp máy tính, chữ ký số, tài khoản hệ thống và phần mềm kê khai.","Lương thỏa thuận + phụ cấp trách nhiệm; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày."],"tuan_thu":["Chịu trách nhiệm Kế toán trưởng theo Luật Kế toán 88/2015/QH13 và các chuẩn mực kế toán.","Tuân thủ pháp luật thuế; kê khai trung thực, đầy đủ, đúng hạn.","Bảo mật số liệu tài chính, lương thưởng theo Điều 21 BLLĐ và quy chế công ty.","Không lập hai hệ thống sổ sách; từ chối và báo cáo mọi yêu cầu hạch toán trái pháp luật."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='KTT';

-- ---------- NV_KT ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Nhân viên Kế toán', cap_bac='Nhân viên', bao_cao_cho='KTT',
 muc_dich=$jd$Ghi nhận chính xác, kịp thời các nghiệp vụ kế toán phát sinh (hóa đơn, thu chi, công nợ) trên hệ thống; hỗ trợ Kế toán trưởng lập báo cáo và bảo đảm chứng từ đầy đủ, hợp lệ, hợp pháp.$jd$,
 trach_nhiem=$jd$["Ghi nhận hóa đơn bán/mua vào hệ thống; kiểm tra tính hợp lệ, hợp pháp của hóa đơn chứng từ.","Lập phiếu thu/chi gắn công nợ và mã bán hàng; trình duyệt theo quy trình.","Theo dõi công nợ phải thu/phải trả; đối chiếu và nhắc hạn thanh toán.","Phát hành hóa đơn điện tử cho khách hàng sau nghiệm thu/chốt sổ.","Nhập liệu và lưu trữ chứng từ gốc khoa học, dễ truy xuất phục vụ kiểm tra.","Hỗ trợ tính lương: kiểm tra dữ liệu công, phụ cấp trước khi trình KTT.","Đối chiếu ngân hàng, quỹ tiền mặt định kỳ; báo cáo chênh lệch ngay khi phát hiện.","Hỗ trợ lập báo cáo thuế, thống kê và cung cấp số liệu khi kiểm toán."]$jd$,
 quyen_han=$jd$["Yêu cầu bộ phận liên quan bổ sung chứng từ trước khi hạch toán.","Từ chối tiếp nhận hóa đơn, chứng từ không hợp lệ (báo cáo KTT).","Truy cập phân hệ kế toán theo quyền được cấp.","Đề xuất cải tiến quy trình luân chuyển chứng từ."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học Kế toán - Tài chính.","kinh_nghiem":"≥ 1 năm kế toán doanh nghiệp; ưu tiên biết kế toán giá thành dự án.","ky_nang":["Hạch toán & định khoản","Hóa đơn điện tử","Excel","Cẩn thận - chính xác","Sắp xếp chứng từ"],"chung_chi":"","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7 tại văn phòng.","Được cấp máy tính, tài khoản hệ thống và phần mềm liên quan.","Lương thỏa thuận; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày."],"tuan_thu":["Thực hiện đúng hợp đồng lao động, nội quy lao động theo BLLĐ 45/2019/QH14.","Tuân thủ Luật Kế toán 2015: ghi nhận trung thực, không sửa xóa chứng từ.","Bảo mật số liệu tài chính, lương thưởng theo Điều 21 BLLĐ.","Báo cáo KTT ngay khi phát hiện sai lệch, gian lận."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='NV_KT';

-- ---------- TP_DA ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Trưởng phòng Dự án', cap_bac='Quản lý', bao_cao_cho='CEO',
 muc_dich=$jd$Chịu trách nhiệm toàn diện về thiết kế, thi công, nghiệm thu và hiệu quả các dự án xử lý nước/nước thải: đúng tiến độ, đúng ngân sách, đạt chuẩn xả thải QCVN và an toàn tuyệt đối trên công trường.$jd$,
 trach_nhiem=$jd$["Tổ chức khảo sát, thẩm định công nghệ và phê duyệt phương án thiết kế cơ sở/chi tiết.","Lập kế hoạch dự án: tiến độ, ngân sách, nhân lực, mốc nghiệm thu trên hệ thống.","Duyệt chi phí dự án trong hạn mức 5 triệu đồng; kiểm soát phát sinh, trình cấp trên phần vượt.","Duyệt khối lượng thi công, nhật ký công trường và các mốc tiến độ do nhân viên ghi nhận.","Quản lý rủi ro và an toàn lao động công trường theo Luật ATVSLĐ; dừng thi công khi mất an toàn.","Điều phối với Cung ứng về vật tư thiết bị, với Kinh doanh về cam kết hợp đồng khách hàng.","Nghiệm thu nội bộ và cùng khách hàng; bảo đảm nước sau xử lý đạt QCVN cam kết.","Tổng kết dự án: hiệu quả ngân sách, bài học kinh nghiệm, hồ sơ hoàn công đầy đủ."]$jd$,
 quyen_han=$jd$["Duyệt chi phí, khối lượng, mốc tiến độ dự án trong hạn mức được giao.","Phân công, điều động nhân sự kỹ thuật giữa các dự án.","Dừng thi công khi phát hiện nguy cơ mất an toàn hoặc sai thiết kế.","Đề xuất thay đổi phương án kỹ thuật, phát sinh chi phí lên Giám đốc.","Đại diện công ty làm việc kỹ thuật với khách hàng, tư vấn giám sát."]$jd$,
 yeu_cau=$jd${"hoc_van":"Đại học Kỹ thuật môi trường, Cấp thoát nước, Hóa hoặc tương đương.","kinh_nghiem":"≥ 5 năm thiết kế/thi công hệ thống xử lý nước, ≥ 2 năm quản lý dự án.","ky_nang":["Công nghệ xử lý nước (hóa lý, sinh học, màng RO/MBR)","Quản lý dự án & tiến độ","Dự toán - kiểm soát ngân sách","AutoCAD/P&ID","Quản lý an toàn công trường"],"chung_chi":"Ưu tiên chứng chỉ hành nghề thiết kế/giám sát xây dựng; chứng nhận huấn luyện ATVSLĐ nhóm quản lý theo NĐ 44/2016/NĐ-CP.","dieu_kien":["Thời giờ làm việc 8 giờ/ngày; thường xuyên công tác công trường trong/ngoài thành phố.","Được cấp phương tiện bảo hộ, thiết bị đo, laptop và chi phí công tác.","Môi trường kết hợp văn phòng - công trường; khám sức khỏe định kỳ theo Luật ATVSLĐ.","Lương thỏa thuận + thưởng dự án; BHXH/BHYT/BHTN đầy đủ."],"tuan_thu":["Chịu trách nhiệm ATVSLĐ tại công trường theo Luật ATVSLĐ 84/2015/QH13 và NĐ 06/2021/NĐ-CP về quản lý chất lượng công trình.","Bảo đảm dự án tuân thủ giấy phép môi trường, QCVN xả thải (Luật BVMT 72/2020/QH14).","Thực hiện đúng nội quy lao động, quy trình dự án theo BLLĐ 2019.","Bảo mật hồ sơ thiết kế, công nghệ theo Điều 21 BLLĐ."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='TP_DA';

-- ---------- NV_DA ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Nhân viên Dự án (giám sát thực địa)', cap_bac='Nhân viên', bao_cao_cho='TP_DA',
 muc_dich=$jd$Giám sát thi công, lắp đặt và vận hành thử hệ thống xử lý nước tại hiện trường theo đúng thiết kế, tiến độ và tiêu chuẩn an toàn; là mắt xích bảo đảm chất lượng công trình và dữ liệu hiện trường chính xác trên hệ thống.$jd$,
 trach_nhiem=$jd$["Giám sát nhà thầu/đội thi công lắp đặt thiết bị theo bản vẽ, biện pháp thi công đã duyệt.","Kiểm tra vật tư thiết bị đến công trường: chủng loại, số lượng, chứng chỉ chất lượng.","Theo dõi vận hành thử: lấy mẫu, đo đạc chỉ tiêu (pH, COD, SS...), hiệu chỉnh cùng kỹ thuật.","Ghi nhật ký công trường, cập nhật khối lượng hoàn thành và mốc tiến độ lên hệ thống (chờ duyệt).","Phát hiện, báo cáo kịp thời sai khác thiết kế, phát sinh kỹ thuật và rủi ro an toàn.","Đôn đốc tuân thủ ATVSLĐ, PCCC trên công trường: trang bị bảo hộ, rào chắn, biển báo.","Tham gia nghiệm thu từng phần và tổng thể với khách hàng, tư vấn giám sát.","Hoàn thiện hồ sơ hoàn công phần được giao: biên bản, ảnh, số liệu thí nghiệm."]$jd$,
 quyen_han=$jd$["Ghi nhận nhật ký, khối lượng thi công trên hệ thống (chờ Trưởng phòng duyệt).","Yêu cầu đội thi công dừng hạng mục khi phát hiện sai thiết kế hoặc mất an toàn (báo cáo ngay TP_DA).","Từ chối xác nhận vật tư sai chủng loại, thiếu chứng chỉ.","Đề xuất phương án xử lý phát sinh kỹ thuật."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học Kỹ thuật môi trường, Cấp thoát nước, Xây dựng hoặc liên quan.","kinh_nghiem":"≥ 1 năm thi công/giám sát hệ thống xử lý nước hoặc công trình kỹ thuật.","ky_nang":["Đọc bản vẽ P&ID, bản vẽ thi công","Giám sát lắp đặt cơ - điện","Lấy mẫu & đo nhanh chất lượng nước","Lập biên bản, báo cáo hiện trường","An toàn lao động"],"chung_chi":"Chứng nhận huấn luyện ATVSLĐ theo NĐ 44/2016/NĐ-CP (công ty tổ chức nếu chưa có).","dieu_kien":["Làm việc chủ yếu tại công trường theo dự án; 8 giờ/ngày, có thể làm thêm giờ theo tiến độ (đúng giới hạn BLLĐ).","Được cấp đầy đủ phương tiện bảo hộ cá nhân, thiết bị đo và hỗ trợ chi phí công tác, lưu trú.","Môi trường công trường: ngoài trời, tiếng ồn, hóa chất - yêu cầu sức khỏe tốt; khám sức khỏe định kỳ.","Lương thỏa thuận + phụ cấp công trường; BHXH/BHYT/BHTN, bảo hiểm tai nạn 24/7."],"tuan_thu":["Chấp hành nghiêm Luật ATVSLĐ 84/2015/QH13; sử dụng đầy đủ PTBH; từ chối làm việc khi không bảo đảm an toàn (Điều 6 Luật ATVSLĐ).","Thực hiện nội quy công trường của công ty và của chủ đầu tư.","Ghi nhận số liệu trung thực; nghiêm cấm xác nhận khống khối lượng.","Tuân thủ quy định môi trường: quản lý chất thải thi công đúng nơi quy định."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='NV_DA';

-- ---------- NV_KTH ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Nhân viên Kỹ thuật', cap_bac='Nhân viên', bao_cao_cho='TP_DA',
 muc_dich=$jd$Lắp đặt, vận hành, bảo trì và xử lý sự cố các hệ thống xử lý nước/nước thải tại công trình và trạm cho thuê; bảo đảm hệ thống chạy ổn định, nước đầu ra đạt chuẩn cam kết và thiết bị được chăm sóc đúng định kỳ.$jd$,
 trach_nhiem=$jd$["Lắp đặt, đấu nối cơ - điện thiết bị hệ thống xử lý nước theo bản vẽ thiết kế.","Vận hành thử, hiệu chỉnh thông số công nghệ (pH, hóa chất châm, áp màng RO/MBR, dòng điện EC...).","Thực hiện bảo trì định kỳ theo lịch trên hệ thống: vệ sinh màng, thay vật tư tiêu hao, bôi trơn, kiểm tra điện.","Trực xử lý sự cố theo phân công; chẩn đoán nguyên nhân, khắc phục và báo cáo trong SLA.","Theo dõi chất lượng nước đầu vào/ra bằng thiết bị đo nhanh; lấy mẫu gửi phân tích định kỳ.","Ghi nhật ký vận hành - bảo trì, cập nhật vật tư thay thế và giờ chạy thiết bị lên hệ thống.","Hướng dẫn nhân sự vận hành của khách hàng sử dụng hệ thống đúng quy trình.","Đề xuất vật tư dự phòng, cải tiến kỹ thuật giúp giảm chi phí vận hành."]$jd$,
 quyen_han=$jd$["Đề xuất vật tư, thiết bị thay thế phục vụ bảo trì, sửa chữa.","Ghi nhận khối lượng, nhật ký kỹ thuật trên hệ thống (chờ duyệt).","Tạm dừng vận hành thiết bị khi phát hiện nguy cơ mất an toàn hoặc hư hỏng nặng, báo cáo ngay cấp trên.","Yêu cầu khách hàng phối hợp điều kiện vận hành (điện, nước, hóa chất) theo hợp đồng."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học Kỹ thuật môi trường, Điện - Điện tử, Cơ khí hoặc Tự động hóa.","kinh_nghiem":"≥ 1 năm lắp đặt/vận hành/bảo trì hệ thống xử lý nước hoặc thiết bị công nghiệp.","ky_nang":["Đọc bản vẽ P&ID, sơ đồ điện","Điện công nghiệp & tủ điều khiển","Vận hành RO/MBR/EC/lọc áp lực","Sử dụng thiết bị đo nhanh (pH, TDS, DO...)","Kỹ năng xử lý sự cố"],"chung_chi":"Chứng chỉ an toàn điện và huấn luyện ATVSLĐ nhóm 3 theo NĐ 44/2016/NĐ-CP (công ty hỗ trợ đào tạo nếu chưa có).","dieu_kien":["Làm việc tại công trình/trạm xử lý theo phân công; 8 giờ/ngày, có ca trực sự cố theo lịch (bảo đảm nghỉ bù theo BLLĐ).","Được cấp đầy đủ phương tiện bảo hộ, dụng cụ nghề và thiết bị đo.","Môi trường tiếp xúc hóa chất, điện, không gian kín - tuân thủ nghiêm quy trình an toàn; khám sức khỏe định kỳ + độc hại.","Lương thỏa thuận + phụ cấp hiện trường/độc hại theo quy định; BHXH/BHYT/BHTN, bảo hiểm tai nạn 24/7."],"tuan_thu":["Chấp hành Luật ATVSLĐ 84/2015/QH13: quy trình làm việc trong không gian kín, an toàn điện, an toàn hóa chất (đọc MSDS trước khi thao tác).","Thực hiện nghiêm quy trình vận hành chuẩn (SOP) của từng hệ thống; không tự ý thay đổi thông số ngoài phạm vi.","Quản lý chất thải nguy hại phát sinh khi bảo trì theo quy định môi trường.","Trung thực số liệu vận hành; bảo mật công nghệ của công ty theo Điều 21 BLLĐ."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='NV_KTH';

-- ---------- NV_THUE ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Nhân viên Cho thuê thiết bị', cap_bac='Nhân viên', bao_cao_cho='CEO',
 muc_dich=$jd$Quản lý danh mục tài sản cho thuê (hệ thống, thiết bị xử lý nước) và vòng đời hợp đồng thuê: từ ký kết, bàn giao, thu phí định kỳ đến thu hồi; tối đa hóa tỷ lệ khai thác tài sản và kiểm soát chi phí vận hành từng trạm.$jd$,
 trach_nhiem=$jd$["Quản lý hồ sơ tài sản cho thuê trên hệ thống: tình trạng, vị trí, khách thuê, giá thuê.","Soạn thảo, theo dõi hợp đồng thuê: hiệu lực, gia hạn, thanh lý; nhắc hạn trước 30 ngày.","Lập hóa đơn thu phí thuê định kỳ; theo dõi công nợ thuê và đôn đốc thanh toán.","Ghi nhận chi phí vận hành từng trạm theo mã bán hàng (điện, hóa chất, nhân công, vật tư).","Phối hợp kỹ thuật lập lịch bảo trì tài sản; theo dõi hoàn thành đúng hạn.","Kiểm kê tài sản cho thuê định kỳ; đánh giá khấu hao, đề xuất thanh lý tài sản kém hiệu quả.","Tổng hợp báo cáo P&L từng trạm cho thuê theo tháng.","Tiếp nhận yêu cầu của khách thuê, điều phối xử lý trong cam kết dịch vụ."]$jd$,
 quyen_han=$jd$["Lập và trình hợp đồng thuê, hóa đơn thu phí trên hệ thống.","Nhắc nợ, đề xuất tạm dừng dịch vụ với khách thuê quá hạn kéo dài (trình duyệt).","Đề xuất giá thuê, điều chỉnh giá khi tái ký.","Đề xuất sửa chữa lớn, thanh lý tài sản."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học Kinh tế, Kỹ thuật hoặc liên quan.","kinh_nghiem":"≥ 1 năm quản lý tài sản/hợp đồng dịch vụ; hiểu thiết bị ngành nước là lợi thế.","ky_nang":["Quản lý hợp đồng","Theo dõi công nợ","Phân tích chi phí - P&L cơ bản","Excel & hệ thống quản lý","Giao tiếp khách hàng"],"chung_chi":"","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7; đi kiểm tra trạm cho thuê định kỳ.","Được cấp máy tính, tài khoản hệ thống, chi phí đi lại theo quy chế.","Lương thỏa thuận; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày."],"tuan_thu":["Thực hiện đúng hợp đồng lao động, nội quy lao động theo BLLĐ 45/2019/QH14.","Quản lý tài sản công ty trung thực; kiểm kê đúng kỳ, báo cáo mất mát hư hỏng kịp thời.","Bảo mật điều khoản hợp đồng, giá thuê theo Điều 21 BLLĐ.","Chấp hành ATVSLĐ khi công tác tại trạm xử lý."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='NV_THUE';

-- ---------- NV_HCNS ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Nhân viên Hành chính - Nhân sự', cap_bac='Nhân viên', bao_cao_cho='CEO',
 muc_dich=$jd$Thực hiện công tác nhân sự - tiền lương - hành chính của công ty đúng pháp luật lao động: hồ sơ nhân sự, chấm công, tính lương, BHXH, tuyển dụng và chăm lo đời sống người lao động.$jd$,
 trach_nhiem=$jd$["Quản lý hồ sơ nhân sự, hợp đồng lao động: ký mới, gia hạn, phụ lục đúng loại và thời hạn theo BLLĐ 2019.","Chấm công, tổng hợp tăng ca - nghỉ phép; nhập dữ liệu kỳ lương trên hệ thống trình KTT duyệt.","Kê khai, báo tăng giảm BHXH/BHYT/BHTN đúng hạn; giải quyết chế độ ốm đau, thai sản cho người lao động.","Đăng ký mã số thuế TNCN, người phụ thuộc; hỗ trợ quyết toán thuế TNCN hằng năm.","Tổ chức tuyển dụng: đăng tin, sàng lọc, phỏng vấn, thủ tục nhận việc và hội nhập.","Theo dõi đánh giá KPI, đề xuất khen thưởng - kỷ luật đúng trình tự Điều 122 BLLĐ.","Quản lý hành chính: văn thư, con dấu, văn phòng phẩm, tài sản văn phòng, sự kiện nội bộ.","Tổ chức khám sức khỏe định kỳ, huấn luyện ATVSLĐ và cập nhật nội quy lao động khi luật thay đổi."]$jd$,
 quyen_han=$jd$["Yêu cầu nhân viên cung cấp hồ sơ, chứng từ nhân sự đúng hạn.","Nhập và điều chỉnh dữ liệu công - phép - tăng ca (có kiểm tra chéo).","Đề xuất chính sách phúc lợi, khen thưởng, đào tạo.","Liên hệ cơ quan BHXH, thuế, lao động địa phương theo ủy quyền."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học Quản trị nhân lực, Luật, Kinh tế hoặc liên quan.","kinh_nghiem":"≥ 2 năm C&B hoặc HCNS tổng hợp; nắm vững BHXH và thuế TNCN.","ky_nang":["Pháp luật lao động - BHXH","Tính lương (C&B)","Tuyển dụng","Soạn thảo văn bản hành chính","Excel & phần mềm nhân sự"],"chung_chi":"Ưu tiên chứng chỉ nghiệp vụ C&B hoặc quản trị nhân sự.","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7 tại văn phòng.","Được cấp máy tính, tài khoản hệ thống nhân sự - lương.","Lương thỏa thuận; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày."],"tuan_thu":["Thực hiện đúng BLLĐ 45/2019/QH14, Luật BHXH 58/2014/QH13 và Luật Việc làm trong mọi nghiệp vụ.","Bảo mật tuyệt đối dữ liệu lương, hồ sơ nhân sự theo Điều 21 BLLĐ và NĐ 13/2023/NĐ-CP.","Thực hiện quy trình xử lý kỷ luật đúng trình tự, bảo đảm quyền của người lao động.","Trung thực số liệu công - lương; nghiêm cấm chỉnh sửa dữ liệu ngoài quy trình."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='NV_HCNS';

-- ---------- ADMIN ----------
UPDATE mo_ta_cong_viec SET
 chuc_danh='Quản trị Hệ thống (Admin/IT)', cap_bac='Nhân viên', bao_cao_cho='CEO',
 muc_dich=$jd$Bảo đảm hệ thống quản trị SVWS và hạ tầng CNTT của công ty hoạt động ổn định, an toàn, bảo mật; quản lý tài khoản - phân quyền người dùng và hỗ trợ kỹ thuật cho toàn bộ nhân viên.$jd$,
 trach_nhiem=$jd$["Quản lý tài khoản người dùng hệ thống SVWS: tạo mới, đổi vai trò, khóa/mở, đặt lại mật khẩu theo yêu cầu được duyệt.","Duy trì ma trận phân quyền theo quyết định của Giám đốc; rà soát quyền định kỳ.","Theo dõi vận hành hệ thống (uptime, lỗi, sao lưu dữ liệu); phối hợp nhà cung cấp hạ tầng xử lý sự cố.","Sao lưu định kỳ cơ sở dữ liệu và tệp lưu trữ; kiểm tra khả năng phục hồi.","Quản lý thiết bị CNTT: máy tính, mạng, email công ty; cài đặt và cập nhật phần mềm.","Hướng dẫn, hỗ trợ nhân viên sử dụng hệ thống; tiếp nhận và xử lý yêu cầu hỗ trợ.","Giám sát an ninh: cảnh báo đăng nhập bất thường, rà soát audit log định kỳ.","Đề xuất nâng cấp, cải tiến hệ thống phục vụ nghiệp vụ mới."]$jd$,
 quyen_han=$jd$["Quản trị tài khoản, phân quyền hệ thống theo phê duyệt của Giám đốc.","Tạm khóa tài khoản có dấu hiệu bị chiếm đoạt hoặc vi phạm bảo mật (báo cáo ngay).","Truy cập audit log phục vụ rà soát an ninh.","Yêu cầu người dùng tuân thủ chính sách mật khẩu, bảo mật thiết bị."]$jd$,
 yeu_cau=$jd${"hoc_van":"Cao đẳng/Đại học CNTT hoặc liên quan.","kinh_nghiem":"≥ 2 năm quản trị hệ thống/hỗ trợ CNTT doanh nghiệp.","ky_nang":["Quản trị người dùng & phân quyền","Cơ sở dữ liệu cơ bản (PostgreSQL)","Sao lưu - phục hồi","Mạng & thiết bị văn phòng","An toàn thông tin cơ bản"],"chung_chi":"Ưu tiên chứng chỉ quản trị hệ thống/an toàn thông tin.","dieu_kien":["Thời giờ làm việc 8 giờ/ngày, thứ 2 - thứ 7; hỗ trợ từ xa ngoài giờ khi có sự cố nghiêm trọng (tính làm thêm giờ theo BLLĐ).","Được cấp máy tính, công cụ quản trị và tài khoản đặc quyền có kiểm soát.","Lương thỏa thuận; BHXH/BHYT/BHTN đầy đủ; nghỉ phép năm 12 ngày."],"tuan_thu":["Tuân thủ Luật An toàn thông tin mạng 2015 và NĐ 13/2023/NĐ-CP về bảo vệ dữ liệu cá nhân.","Không truy cập, tiết lộ dữ liệu nghiệp vụ ngoài phạm vi nhiệm vụ; mọi thao tác đặc quyền được ghi vết.","Thực hiện đúng nội quy lao động theo BLLĐ 45/2019/QH14.","Bảo mật thông tin đăng nhập đặc quyền; bàn giao đầy đủ khi thay đổi vị trí."]}$jd$,
 cap_nhat_luc=now()
WHERE vai_tro='ADMIN';

COMMIT;
